spring.application.name=sto

# ===== Telegram Bot =====
telegram.bot.token=8799144262:AAGTE04oacUUkRsOuhTUMqbis97R-hC4-1U
telegram.bot.username=sto_vyazovsky_bot

# Список chat_id через запятую — у кого есть права на команды бота
telegram.admin.ids=137733903, 866916563

# chat_id, куда падают заявки с сайта (один)
telegram.chat.id=866916563

# Включить long-polling бота
telegram.bot.enabled=true

# ===== Внешние ссылки для меню пользователя =====
sto.site.url=https://mousy-herald-womanless.ngrok-free.dev/
sto.telegram.main=https://t.me/STOVyazovskiy

# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/vyazovskyy?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true